name: .NET Core Console CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build-and-test:
 
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
       
    env:
      Solution_Name: Lab5_Library.sln
      Test_Project_Path: ..\Library_Test\Lab6_Library_Test.csproj
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
 
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
 
    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Solution_Name }}
 
    - name: Build solution
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore
 
    - name: Test and publish results
      run: |
        dotnet test ${{ env.Test_Project_Path }} --no-restore --verbosity normal
